"use client";

import Link from "next/link";

const features = [
  ["01", "Factures professionnelles", "Créez des documents élégants en quelques clics, avec TVA, coordonnées et PDF prêt à envoyer."],
  ["02", "TVA calculée automatiquement", "Les montants HT, TVA et TTC restent cohérents, même avec plusieurs lignes et plusieurs taux."],
  ["03", "Paiements suivis", "Visualisez les factures payées, en attente ou en retard et relancez vos clients au bon moment."],
  ["04", "Clients et équipe", "Gardez vos fiches clients, vos produits et vos accès d’équipe dans un seul espace."],
];
const problems = [["!", "Factures non professionnelles", "Des documents bricolés qui ralentissent les signatures et donnent une image amateur."], ["%", "Calcul manuel de TVA", "Des erreurs d’arrondi et des calculs fastidieux avant chaque déclaration."], ["◷", "Suivi des paiements impossible", "Des factures oubliées et une trésorerie difficile à anticiper."]];
const testimonials = [["MD", "Mamadou Diallo", "Fondateur BTP & Rénovation", "Avant FacturePro, je recalculais la TVA sur Excel. Aujourd’hui, j’envoie des factures propres depuis mon téléphone."], ["AK", "Awa Kouamé", "Directrice Agence Marketing", "La présentation nette et le suivi des paiements nous aident à relancer nos clients au bon moment."], ["IT", "Ibrahim Traoré", "Grossiste matériel industriel", "Créer un client et sortir une facture prend deux minutes, même avec une connexion moyenne."]];

export function LandingPage() {
  return <main className="landing-page">
    <LandingHeader />
    <section className="landing-hero"><div className="landing-dots" /><div className="landing-container landing-hero-inner"><div className="landing-pill"><i /> Pensé pour les entrepreneurs africains</div><div className="landing-hero-copy"><h1>Facturez comme un pro.<br /><span>Développez votre activité.</span></h1><p>FacturePro aide les indépendants et les PME à créer des factures professionnelles, suivre leurs encaissements et garder une trésorerie claire.</p><div className="landing-actions"><Link className="landing-primary" href="/login">Commencer gratuitement <b>→</b></Link><Link className="landing-secondary" href="#fonctionnalites"><span>▶</span> Découvrir la plateforme</Link></div></div><LandingMockup /></div></section>
    <section className="landing-proof"><div className="landing-container landing-proof-grid"><span><b>✓</b> Conforme à votre activité</span><span><b>◉</b> GNF et devises internationales</span><span><b>⌁</b> Données sécurisées avec Supabase</span></div></section>
    <section className="landing-section landing-problems" id="problemes"><div className="landing-container"><div className="landing-section-intro centered"><span className="landing-eyebrow">Défis quotidiens</span><h2>Pourquoi perdre du temps et de l’argent sur votre <span>facturation ?</span></h2><p>FacturePro remet de la clarté dans les tâches qui ralentissent votre activité.</p></div><div className="landing-feature-grid landing-problem-grid">{problems.map(([icon, title, text]) => <article className="landing-feature" key={title}><div className="landing-feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p><strong>Une gestion plus claire →</strong></article>)}</div></div></section>
    <section className="landing-section" id="fonctionnalites"><div className="landing-container"><div className="landing-section-intro centered"><span className="landing-eyebrow">Nos fonctionnalités clés</span><h2>La plateforme conçue pour faire grandir vos <span>revenus.</span></h2><p>Chaque détail est pensé pour passer moins de temps en comptabilité et plus de temps à développer votre activité.</p></div><div className="landing-feature-grid">{features.map(([number, title, text]) => <article className="landing-feature" key={number}><div className="landing-feature-top"><span className="landing-feature-icon">{number === "01" ? "↗" : number === "02" ? "%" : number === "03" ? "◷" : "♙"}</span><b>{number}</b></div><h3>{title}</h3><p>{text}</p><Link href="/login">En savoir plus <span>→</span></Link></article>)}</div></div></section>
    <section className="landing-section landing-workflow" id="fonctionnement"><div className="landing-container"><div className="landing-section-intro centered"><span className="landing-eyebrow">Démarrage rapide</span><h2>De l’idée au paiement<br /><span>en trois mouvements.</span></h2></div><div className="landing-steps"><LandingStep number="1" title="Créez votre espace" text="Choisissez votre profil, renseignez votre entreprise et commencez sans carte bancaire." /><LandingStep number="2" title="Préparez votre facture" text="Sélectionnez un client, ajoutez vos services et laissez FacturePro calculer les montants." /><LandingStep number="3" title="Envoyez et encaissez" text="Partagez un PDF professionnel, suivez le statut et gardez la main sur votre trésorerie." /></div></div></section>
    <section className="landing-section landing-testimonials" id="temoignages"><div className="landing-container"><div className="landing-section-intro centered"><span className="landing-eyebrow">Retours d’expérience</span><h2>Ce que nos <span>entrepreneurs</span> disent de nous</h2><p>Une facturation plus sérieuse, plus claire et plus simple au quotidien.</p></div><div className="landing-testimonial-grid">{testimonials.map(([initials, author, role, quote]) => <article className="landing-testimonial" key={author}><div className="landing-stars">★★★★★</div><p>“{quote}”</p><footer><b>{initials}</b><span><strong>{author}</strong><small>{role}</small></span></footer></article>)}</div></div></section>
    <section className="landing-section landing-pricing" id="tarifs"><div className="landing-container"><div className="landing-section-intro centered"><span className="landing-eyebrow">Tarifs transparents</span><h2>Des forfaits adaptés au rythme de votre <span>entreprise.</span></h2><p>Commencez gratuitement, puis choisissez la formule qui accompagne votre croissance.</p></div><div className="landing-pricing-grid"><LandingPlan name="Plan Gratuit" price="0" text="Pour tester et facturer vos premières missions." items={["5 factures par mois", "1 utilisateur", "TVA calculée automatiquement", "Export PDF"]} /><LandingPlan featured name="Plan Pro" price="60.000" text="Pour les consultants, PME et commerçants actifs." items={["Factures illimitées", "Paiements et relances", "Modèles personnalisés", "Suivi complet"]} /><LandingPlan name="Plan Business" price="180.000" text="Pour les équipes et entreprises en croissance." items={["Multi-utilisateurs", "Rôles et accès", "Exports avancés", "Support prioritaire"]} /></div></div></section>
    <section className="landing-cta"><div className="landing-container"><div><span className="landing-eyebrow">Votre activité mérite mieux</span><h2>Prêt à facturer<br /><span>avec confiance ?</span></h2><p>Commencez simplement. Construisez une gestion qui grandit avec vous.</p></div><Link className="landing-primary landing-cta-button" href="/login">Créer mon espace <b>→</b></Link></div></section>
    <footer className="landing-footer"><div className="landing-container"><div className="landing-footer-top"><Link className="landing-brand" href="/"><span className="brand-mark">F</span><strong>Facture<span>Pro</span></strong></Link><p>La facturation moderne pour les entrepreneurs qui avancent.</p><div className="landing-footer-links"><Link href="#fonctionnalites">Fonctionnalités</Link><Link href="#fonctionnement">Fonctionnement</Link><Link href="/login">Connexion</Link></div></div><div className="landing-footer-bottom"><span>© 2026 FacturePro</span><span>Fait pour les entreprises qui avancent.</span></div></div></footer>
  </main>;
}

function LandingHeader() {
  return <header className="landing-header"><div className="landing-container landing-nav"><Link className="landing-brand" href="/"><span className="brand-mark">F</span><strong>Facture<span>Pro</span></strong></Link><nav><a href="#problemes">Défis</a><a href="#fonctionnalites">Fonctionnalités</a><a href="#fonctionnement">Fonctionnement</a><a href="#temoignages">Témoignages</a><a href="#tarifs">Tarifs</a></nav><div className="landing-header-actions"><Link className="landing-login" href="/login">Se connecter</Link><Link className="landing-nav-cta" href="/login">Commencer gratuitement <span>→</span></Link></div><Link className="landing-mobile-login" href="/login" aria-label="Se connecter">↗</Link></div></header>;
}

function LandingMockup() {
  return <div className="landing-mockup"><div className="landing-mockup-bar"><span><i /><i /><i /></span><small>app.facturepro.com</small><b>AK</b></div><div className="landing-mockup-content"><aside><strong>Facture<span>Pro</span></strong><em>Vue d’ensemble</em><span>▤ Factures</span><span>♙ Clients</span><span>↔ Paiements</span></aside><div className="landing-mockup-main"><div className="landing-mockup-title"><small>VOTRE ESPACE DE PILOTAGE</small><h3>Bonjour, votre entreprise<span>.</span></h3><p>Une vue claire sur vos ventes et encaissements.</p></div><div className="landing-mockup-metrics"><div><small>Chiffre facturé</small><strong>12.508.000 <i>GNF</i></strong></div><div><small>Encaissé</small><strong>11.000.000 <i>GNF</i></strong></div><div><small>À recevoir</small><strong>1.508.000 <i>GNF</i></strong></div></div><div className="landing-mockup-table"><div><span>ACTIVITÉ RÉCENTE</span><span>EN DIRECT</span></div><div><b>Client professionnel</b><strong>FAC-LOCAL-0001</strong><em>Payée</em><strong>2.500.000 GNF</strong></div><div><b>Entreprise partenaire</b><strong>FAC-LOCAL-0002</strong><em>En attente</em><strong>1.800.000 GNF</strong></div></div></div></div></div>;
}

function LandingStep({ number, title, text }: { number: string; title: string; text: string }) {
  return <article className="landing-step"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>;
}

function LandingPlan({ name, price, text, items, featured = false }: { name: string; price: string; text: string; items: string[]; featured?: boolean }) {
  return <article className={`landing-plan ${featured ? "featured" : ""}`}>{featured && <span className="landing-plan-badge">Le plus populaire</span>}<h3>{name}</h3><p>{text}</p><strong>{price} <small>GNF / mois</small></strong><ul>{items.map((item) => <li key={item}>✓ {item}</li>)}</ul><Link className={featured ? "landing-primary" : "landing-secondary"} href="/login">Commencer</Link></article>;
}
